=== Akhilez/JNTUHLabPrograms/CSE/WT/3. SAX/Employee.dtd
<!ELEMENT empdetails (employee*)>
	<!ELEMENT employee (name,desgn,dept,salary)>
		<!ELEMENT name (#PCDATA)>
		<!ELEMENT desgn (#PCDATA)>
		<!ELEMENT dept (#PCDATA)>
		<!ELEMENT salary (#PCDATA)>
<!ATTLIST employee id CDATA #REQUIRED>

=== Akhilez/JNTUHLabPrograms/CSE/WT/3. SAX/Employees.xml
<?xml version="1.0"?>
<!DOCTYPE catalog SYSTEM "Employee.dtd">
<empdetails>
    <employee id="01">
        <name>shiva</name>
        <desgn>Associate Professor</desgn>
        <dept>IT</dept>
        <salary>52000</salary>
    </employee>

    <employee id="02">
        <name>ravi</name>
        <desgn>Assistant Professor</desgn>
        <dept>cse</dept>
        <salary>48000</salary>
    </employee>

    <employee id="03">
        <name>kiran</name>
        <desgn>Professor</desgn>
        <dept>ece</dept>
        <salary>65000</salary>
    </employee>

    <employee id="04">
        <name>shyam</name>
        <desgn>rector</desgn>
        <dept>cse</dept>
        <salary>95000</salary>
    </employee>
    
    <employee id="05">
        <name>Shashi</name>
        <desgn>professor</desgn>
        <dept>cse</dept>
        <salary>85000</salary>
    </employee>
</empdetails>
